version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 891376989451.dkr.ecr.ap-south-1.amazonaws.com/my-docker-repo
  build:
    commands:
      - echo Build started on date
      - echo Building the Docker image...
      - docker build -t my-docker-image .
      - docker tag my-docker-image:latest 891376989451.dkr.ecr.ap-south-1.amazonaws.com/my-docker-repo:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 891376989451.dkr.ecr.ap-south-1.amazonaws.com/my-docker-repo:latest
      - echo Build completed on date
artifacts:
  files:
    - '*/'