version: 0.2

phases:
  pre_build:
    commands:
      - echo "Skipping ECR login as it's a public repository..."
  build:
    commands:
      - echo "Build started on date"
      - echo "Building the Docker image..."
      - docker build -t my-docker-image .
      - docker tag my-docker-image:latest public.ecr.aws/s6l6e9o1/my-docker-repo:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to public ECR..."
      - docker push public.ecr.aws/s6l6e9o1/my-docker-repo:latest
      - echo "Build completed on date"
artifacts:
  files:
    - '**/*'
